name: 미루고 미루다
author: Herring Cove
baseurl: /jinhee-kang.github.io
description: 미루고 미루다 쓰는 블로그
github: http://www.github.com/JINHEE-KANG
twitter: http://www.twitter.com
linkedin: http://www.linkedin.com
facebook: http://www.facebook.com
email: genie0301@naver.com
location: 37°34'00"N   126°58'41"E
disqus: diqus-JINHEE-KANG

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
